Section 9
lirantal/nodejs-cli-apps-best-practices pull request #79
Opened 2022-02-19 10:00 UTC by UrielOfir

I tried to solve issue #78.
I would be glad to get feedback.

2022-02-19 12:07 UTC, lirantal requested changes

2022-02-19 12:07 UTC, lirantal commented on README.md
> +<table>
This is great but can you convert the HTML table into Markdown syntax for tables? See here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

2022-02-19 12:07 UTC, lirantal commented
Thanks for taking this on @UrielOfir 👏
I added one review item to fix and I'll merge it right after

2022-02-19 12:47 UTC, lirantal requested changes

2022-02-19 12:47 UTC, lirantal commented on README.md
> +| Name  | Description | Npm | Github | Stars and downloads |
```suggestion
| Name  | Description | npm | GitHub | Stars and downloads |
```

2022-02-19 12:47 UTC, lirantal commented on README.md
> +| oclif  | A framework for building a command line interface.  | [Link to npm](https://www.npmjs.com/package/oclif) | [Link to Github](https://github.com/oclif/oclif) | ![](https://img.shields.io/git
```suggestion
| oclif  | A framework for building a command line interface.  | [Link to npm](https://www.npmjs.com/package/oclif) | [Link to GitHub](https://github.com/oclif/oclif) | ![](https://img.shields.io/github/stars/oclif/oclif)![](https://img.shields.io/npm/dt/oclif.svg)
```

2022-02-19 12:47 UTC, lirantal commented on README.md
> +| inquirer  | A collection of common interactive command line user interfaces.  | [Link to npm](https://www.npmjs.com/package/inquirer) | [Link to Github](https://github.com/SBoudrias/Inquirer.js) |!
```suggestion
| inquirer  | A collection of common interactive command line user interfaces.  | [Link to npm](https://www.npmjs.com/package/inquirer) | [Link to GitHub](https://github.com/SBoudrias/Inquirer.js) |![](https://img.shields.io/github/stars/sboudrias/inquirer.js)![](https://img.shields.io/npm/dt/inquirer.svg)
```

2022-02-19 12:47 UTC, lirantal commented on README.md
> +| ink | Ink provides the same component-based UI building experience that React offers in the browser, but for command-line apps. | [Link to npm](https://www.npmjs.com/package/ink) | [Link to Github]
```suggestion
| ink | Ink provides the same component-based UI building experience that React offers in the browser, but for command-line apps. | [Link to npm](https://www.npmjs.com/package/ink) | [Link to GitHub](https://github.com/vadimdemedes/ink) | ![](https://img.shields.io/github/stars/vadimdemedes/ink)![](https://img.shields.io/npm/dt/ink.svg)
```

2022-02-19 12:47 UTC, lirantal commented on README.md
> +|blessed |A curses-like library with a high level terminal interface API for node.js.| [Link to npm](https://www.npmjs.com/package/blessed) | [Link to Github](https://github.com/chjj/blessed) | ![](h
```suggestion
|blessed |A curses-like library with a high level terminal interface API for node.js.| [Link to npm](https://www.npmjs.com/package/blessed) | [Link to GitHub](https://github.com/chjj/blessed) | ![](https://img.shields.io/github/stars/chjj/blessed)![](https://img.shields.io/npm/dt/blessed.svg)
```

2022-02-19 12:47 UTC, lirantal commented
Looks wonderful @UrielOfir thank you ❤️ 
I added a bunch of small suggestions due to proper naming conventions and we're good to merge!

2022-02-19 13:05 UTC, UrielOfir commented
> Looks wonderful @UrielOfir thank you ❤️ I added a bunch of small suggestions due to proper naming conventions and we're good to merge!

I approved your changes :)

2022-02-19 13:17 UTC, lirantal approved these changes

2022-02-19 13:19 UTC, merged

2022-03-04 12:54 UTC, lirantal commented
@UrielOfir do you want to update the Teams section on the readme by adding your contributor card to it too? https://github.com/lirantal/nodejs-cli-apps-best-practices#the-team-

2022-03-05 06:55 UTC, UrielOfir commented
> @UrielOfir do you want to update the Teams section on the readme by adding your contributor card to it too? https://github.com/lirantal/nodejs-cli-apps-best-practices#the-team-

I think I will wait until I'll contribute more.

2022-03-05 21:25 UTC, lirantal commented
@UrielOfir any contribution, small or big, deserves to be celebrated and recognized. Please feel free to add yourself to the README ❤️